apiVersion: v1
kind: Service
metadata:
  name: adressbook-loadbalancer
  labels:
    service: addressbookloadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31222
    protocol: TCP
  selector:
    app: 
