apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addressbookdeplyoment1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook-container
        image: npsoni/tcsapp:8
        ports:
        - containerPort: 8080
